server:
  port: 8081
spring:
  datasource:
    username: root
    password: guofan123456
    url: jdbc:mysql://101.34.107.75:3306/computer_repair_shop?userUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver